CLASS zbp_i_course_mww25 DEFINITION
  PUBLIC
  FINAL
  FOR BEHAVIOR OF zi_course_mww25.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zbp_i_course_mww25 IMPLEMENTATION.
ENDCLASS.
