CLASS zbp_i_progress_mww25 DEFINITION
  PUBLIC
  FINAL
  FOR BEHAVIOR OF zi_progress_mww25.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zbp_i_progress_mww25 IMPLEMENTATION.
ENDCLASS.
